/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tbarlow.view;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static javax.swing.JOptionPane.showMessageDialog;
import tbarlow.controller.Game;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.ListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import tbarlow.controller.LoadGame;
import tbarlow.model.characters.Hero;
import tbarlow.model.characters.Scout;
import tbarlow.model.characters.Thief;
import tbarlow.model.characters.Warmonger;

/**
 *
 * @author Tyron
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    private Hero hero;
    CardLayout cards;
    
    public MainMenu() {
        setFocusableWindowState(true);
        setPreferredSize(new Dimension(700,500));
        
        
        initComponents();
        cards = (CardLayout)MasterPanel.getLayout();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MasterPanel = new javax.swing.JPanel();
        pnlMainMenu = new javax.swing.JPanel();
        pnlSwingy = new javax.swing.JPanel();
        btnSwingy = new javax.swing.JLabel();
        btnNewGame = new javax.swing.JButton();
        btnLoadGame = new javax.swing.JButton();
        pnlNewGame = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbClass = new javax.swing.JComboBox<>();
        btnCreateHero = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnBack2 = new javax.swing.JButton();
        pnlLoadGame = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstHeroes = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        taHeroDetails = new javax.swing.JTextArea();
        btnLoad = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MainMenu");
        setBackground(new java.awt.Color(153, 153, 153));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusableWindowState(false);
        setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        setForeground(new java.awt.Color(153, 153, 255));
        setMinimumSize(new java.awt.Dimension(750, 500));
        setName("Main Menu"); // NOI18N
        setPreferredSize(new java.awt.Dimension(750, 500));
        setSize(new java.awt.Dimension(750, 500));

        MasterPanel.setPreferredSize(new java.awt.Dimension(750, 500));
        MasterPanel.setLayout(new java.awt.CardLayout());

        pnlMainMenu.setMinimumSize(new java.awt.Dimension(750, 500));
        pnlMainMenu.setPreferredSize(new java.awt.Dimension(750, 500));

        pnlSwingy.setBackground(new java.awt.Color(255, 255, 255));

        btnSwingy.setBackground(new java.awt.Color(255, 255, 255));
        btnSwingy.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 48)); // NOI18N
        btnSwingy.setForeground(new java.awt.Color(0, 0, 0));
        btnSwingy.setText("SWINGY");

        javax.swing.GroupLayout pnlSwingyLayout = new javax.swing.GroupLayout(pnlSwingy);
        pnlSwingy.setLayout(pnlSwingyLayout);
        pnlSwingyLayout.setHorizontalGroup(
            pnlSwingyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSwingyLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(btnSwingy)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSwingyLayout.setVerticalGroup(
            pnlSwingyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSwingyLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnSwingy)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        btnNewGame.setBackground(new java.awt.Color(153, 153, 153));
        btnNewGame.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        btnNewGame.setText("New Game");
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGameActionPerformed(evt);
            }
        });

        btnLoadGame.setBackground(new java.awt.Color(153, 153, 153));
        btnLoadGame.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        btnLoadGame.setText("Load Game");
        btnLoadGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainMenuLayout = new javax.swing.GroupLayout(pnlMainMenu);
        pnlMainMenu.setLayout(pnlMainMenuLayout);
        pnlMainMenuLayout.setHorizontalGroup(
            pnlMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainMenuLayout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(pnlMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlSwingy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMainMenuLayout.createSequentialGroup()
                        .addComponent(btnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186)
                        .addComponent(btnLoadGame, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(108, 108, 108))
        );
        pnlMainMenuLayout.setVerticalGroup(
            pnlMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainMenuLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(pnlSwingy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(pnlMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoadGame, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        MasterPanel.add(pnlMainMenu, "mainMenu");

        pnlNewGame.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 24)); // NOI18N
        pnlNewGame.setMinimumSize(new java.awt.Dimension(750, 500));

        jLabel1.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 48)); // NOI18N
        jLabel1.setText("New Game");

        jLabel2.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 36)); // NOI18N
        jLabel2.setText("Create a hero");

        jLabel3.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 24)); // NOI18N
        jLabel3.setText("Class:");

        jLabel4.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 24)); // NOI18N
        jLabel4.setText("Name:");

        cmbClass.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 24)); // NOI18N
        cmbClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbClass.setPreferredSize(new java.awt.Dimension(250, 39));
        cmbClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClassActionPerformed(evt);
            }
        });

        btnCreateHero.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 24)); // NOI18N
        btnCreateHero.setText("Continue");
        btnCreateHero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateHeroActionPerformed(evt);
            }
        });

        txtName.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 24)); // NOI18N
        txtName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtName.setPreferredSize(new java.awt.Dimension(250, 37));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtDescription.setEditable(false);
        txtDescription.setColumns(5);
        txtDescription.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 14)); // NOI18N
        txtDescription.setRows(4);
        txtDescription.setBorder(null);
        jScrollPane1.setViewportView(txtDescription);

        btnBack2.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 24)); // NOI18N
        btnBack2.setText("Back");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNewGameLayout = new javax.swing.GroupLayout(pnlNewGame);
        pnlNewGame.setLayout(pnlNewGameLayout);
        pnlNewGameLayout.setHorizontalGroup(
            pnlNewGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNewGameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
            .addGroup(pnlNewGameLayout.createSequentialGroup()
                .addGroup(pnlNewGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNewGameLayout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlNewGameLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlNewGameLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlNewGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlNewGameLayout.createSequentialGroup()
                                .addComponent(cmbClass, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlNewGameLayout.createSequentialGroup()
                                .addComponent(btnBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCreateHero, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        pnlNewGameLayout.setVerticalGroup(
            pnlNewGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewGameLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(pnlNewGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlNewGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNewGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(cmbClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(pnlNewGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateHero)
                    .addComponent(btnBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        MasterPanel.add(pnlNewGame, "newGame");

        pnlLoadGame.setMinimumSize(new java.awt.Dimension(750, 500));

        jLabel5.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 48)); // NOI18N
        jLabel5.setText("Load Game");

        lstHeroes.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jScrollPane2.setViewportView(lstHeroes);

        taHeroDetails.setEditable(false);
        taHeroDetails.setColumns(20);
        taHeroDetails.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        taHeroDetails.setRows(5);
        jScrollPane3.setViewportView(taHeroDetails);

        btnLoad.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        btnLoad.setText("Load Hero");

        btnBack.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoadGameLayout = new javax.swing.GroupLayout(pnlLoadGame);
        pnlLoadGame.setLayout(pnlLoadGameLayout);
        pnlLoadGameLayout.setHorizontalGroup(
            pnlLoadGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoadGameLayout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addGroup(pnlLoadGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoadGameLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoadGameLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlLoadGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoadGameLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(140, 140, 140))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoadGameLayout.createSequentialGroup()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102)
                                .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103)))))
                .addGap(105, 105, 105))
        );
        pnlLoadGameLayout.setVerticalGroup(
            pnlLoadGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoadGameLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addGap(47, 47, 47)
                .addGroup(pnlLoadGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(pnlLoadGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        MasterPanel.add(pnlLoadGame, "loadGame");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MasterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MasterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadGameActionPerformed
        // TODO add your handling code here:
        cards.show(MasterPanel, "loadGame");
        guiLoadGame();
    }//GEN-LAST:event_btnLoadGameActionPerformed

    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
        // TODO add your handling code here:
        cards.show(MasterPanel, "newGame");
        setFocusableWindowState(true);
        createGameScreen();
    }//GEN-LAST:event_btnNewGameActionPerformed

    private void cmbClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbClassActionPerformed

    private void btnCreateHeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateHeroActionPerformed
        // TODO add your handling code here:
        String heroName = txtName.getText();

        if (heroName.isEmpty()) {
            showMessageDialog(this, "Impossible! You must have a name.");
        }
        else {
            int index = cmbClass.getSelectedIndex();
            hero = new Hero(heroName);
            //rungame
            switch (index) {
                case 0:
                hero = new Thief(heroName);
                break;
                case 1:
                hero = new Warmonger(heroName);
                break;
                case 2:
                hero = new Scout(heroName);
                break;
            }
        }
    }//GEN-LAST:event_btnCreateHeroActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       
        cards.show(MasterPanel, "mainMenu");
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed

        cards.show(MasterPanel, "mainMenu");
    }//GEN-LAST:event_btnBack2ActionPerformed

    public void createGameScreen() {
        pnlMainMenu.setVisible(false);
        txtName.setEditable(true);
        
        txtDescription.setLineWrap(true);
        final Hero[] heroes = {new Thief(), new Warmonger(), new Scout()};
        DefaultComboBoxModel heroClasses = new DefaultComboBoxModel();
        for (Hero hero: heroes) {
            heroClasses.addElement(hero.heroType);
            //txtDescription.append(hero.heroType + ": \n" + hero.description + "\n");
        }
        cmbClass.setModel(heroClasses);
        txtDescription.setText(heroes[0].description);
        
        cmbClass.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent ie) {
                //throw new UnsupportedOperationException("Not supported yet.");
                if (ie.getStateChange() == ItemEvent.SELECTED) {
                    String desc = heroes[cmbClass.getSelectedIndex()].description;
                    txtDescription.setText(desc);
                }
            }
        });
    }
    
    public void guiLoadGame() {
        LoadGame loadGame = new LoadGame(); 
        
        final List<Hero> heroList = loadGame.LoadHeroList("heroes.txt");
        if (heroList.size() == 0) {
            lstHeroes.removeAll();
            taHeroDetails.removeAll();
            return;
        }
        DefaultListModel<String> heroes = new DefaultListModel<>();
        for (Hero hero: heroList) {
           heroes.addElement(hero.getName());
           System.out.println(hero.getName());
        }
        
        lstHeroes.setModel(heroes);
        
        lstHeroes.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                if (!lstHeroes.getValueIsAdjusting()) {
                    Hero hero = heroList.get(lstHeroes.getSelectedIndex());
                    String desc;
                    desc = "Type - " + hero.heroType + "\n" + 
                           "Level - " + hero.getLevel() + "\n" +
                           "Attack - " + hero.getAttack() + "\n" +
                           "Defense - " + hero.getDefense() + "\n" +
                           "Health - " + hero.getMaxhp() + "\n" + 
                            EquipmentString(hero);
                    
                    taHeroDetails.setText(desc);
                }
            }
        });
    }
    
   public String EquipmentString(Hero hero) {
       String eqString = "";
       if (hero.getArmour() != null || hero.getHelm() != null || hero.getWeapon() != null) {
            if (hero.getHelm() != null) {
                eqString += hero.getHelm().getName() + " - " + hero.getHelm().getAmount() + "hp\n";
            }
            if (hero.getArmour() != null) {
                eqString += hero.getArmour().getName() + ": " + hero.getArmour().getAmount() + "def\n";
            }
            if (hero.getWeapon() != null) {
                eqString += hero.getWeapon().getName() + ": " + hero.getWeapon().getAmount() + "att";
            }
        }
       return eqString;
   }
    
    public void Game() {
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MasterPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnCreateHero;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnLoadGame;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JLabel btnSwingy;
    private javax.swing.JComboBox<String> cmbClass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lstHeroes;
    private javax.swing.JPanel pnlLoadGame;
    private javax.swing.JPanel pnlMainMenu;
    private javax.swing.JPanel pnlNewGame;
    private javax.swing.JPanel pnlSwingy;
    private javax.swing.JTextArea taHeroDetails;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
